### PR TITLE
2 new sudo commands

### PR DESCRIPTION
**Pull request by imtherealF1**
one is for changing the privacy policy of a user, and one for changing the donation policy, works fine, tested!

### CODE REVIEW

**Comment by RE-alt2** [comment]
this def made the bot get destroyed up 💀

**Comment by imtherealF1** [comment]
@RE-alt2 wdym, the code works fine

**Comment by RE-alt2** [comment]
@imtherealF1 it actually made the code give an error each time you try to execute it

**Comment by imtherealF1** [comment]
that's weird since i tested it, ill have a look

**Pull request merged**
