### PR TITLE
[player] Init Rebirth System

### PR DESCRIPTION
**Pull request by arrayunderscore**
Simple rebirth system that can be upgraded

### CODE REVIEW

**Comment by imtherealF1** [comment]
this is only to try fixing the conflicts.

**Comment by imtherealF1** [comment]
i genuinely dont know why they conflict

**Comment by imtherealF1** [comment]
actually, what i am going to do is open seperate prs with the commands, so that i avoid the conflicts.

**Review by imtherealF1 — CHANGES_REQUESTED** [review]
you need to make the responses better and more "formal".

**Comment by arrayunderscore** [comment]
like? how make it more formal?

**Comment by arrayunderscore** [comment]
would love to see ur input on them then, tell me what needs to change

**Review by imtherealF1 — APPROVED** [review]

**Pull request merged**
